blank_issues_enabled: true
contact_links:
  - name: "ğŸ™ Q&A - GitHub Discussions"
    url: https://github.dev/idealprojects/maphero-native/discussions/categories/q-a
    about: If you have a question about using MapHero Native
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://slack.openstreetmap.us/
    about: "Join #maphero-native on the Open Street Map Slack"

